mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
sharding:
  jdbc:
    datasource:
      names: shard_0, shard_1
      shard_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.88.121:3306/shard_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: jbt1234
      shard_1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.88.121:3306/shard_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: jbt1234
    # 单库分表策略
    config:
      sharding:
        tables:
          user:
            actual-data-nodes: shard_${0..1}.user
            database-strategy:
              standard:
                sharding-column: id
                # 精确分片算法，用于=和IN
                precise-algorithm-class-name: com.hhx.shard.algorithm.PreciseShardbaseDataBase


